services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: ${UID:-1000}:${GID:-1000}
    group_add:
      - '${RENDER_GROUP_ID}'
    environment:
      - JELLYFIN_PublishedServerUrl=${EXTERNAL_URL}
    volumes:
      - ${JELLYFIN_CONFIG_FOLDER:-./config}:/config
      - ${JELLYFIN_CACHE_FOLDER:-./cache}:/cache
      - /usr/share/fonts:/usr/local/share/fonts/custom
      - ${TVSHOWS_FOLDER}:/data/tvshows:ro
      - ${ANIMES_FOLDER}:/data/animes:ro
      - ${MOVIES_FOLDER}:/data/movies:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${JELLYFIN_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}
